const goods = [
  {
    id: 1,
    title: "Teddy Bear",
    price: 30.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35009,
    width: 38,
    height: 32,
    length: 24,
    weight: 25,
    type: "stuffed",
  },
  {
    id: 2,
    title: "Happy Flower",
    price: 38.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35013,
    width: 30,
    height: 41,
    length: 55,
    weight: 99,
    type: "wooden",
  },
  {
    id: 3,
    title: "Mega Plush Toy",
    price: 38.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35010,
    width: 30,
    height: 31,
    length: 20,
    weight: 22,
    type: "stuffed",
  },
  {
    id: 4,
    title: "Lift Machine",
    price: 24.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35014,
    width: 66,
    height: 75,
    length: 22,
    weight: 66,
    type: "wooden",
  },
  {
    id: 5,
    title: "Wooden Camera",
    price: 16.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35015,
    width: 15,
    height: 19,
    length: 15,
    weight: 20,
    type: "wooden",
  },
  {
    id: 6,
    title: "Cute Dog",
    price: 24.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35011,
    width: 32,
    height: 22,
    length: 26,
    weight: 29,
    type: "stuffed",
  },
  {
    id: 7,
    title: "Little Rabbit",
    price: 32.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35016,
    width: 22,
    height: 24,
    length: 23,
    weight: 55,
    type: "wooden",
  },
  {
    id: 8,
    title: "Little Friend",
    price: 27.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35012,
    width: 28,
    height: 41,
    length: 60,
    weight: 44,
    type: "stuffed",
  },
  {
    id: 9,
    title: "Rainbow Truck",
    price: 28.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35009,
    width: 38,
    height: 32,
    length: 24,
    weight: 25,
    type: "wooden",
  },
  {
    id: 10,
    title: "Christmas Deer",
    price: 38.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35010,
    width: 30,
    height: 31,
    length: 20,
    weight: 22,
    type: "stuffed",
  },
  {
    id: 11,
    title: "Cute Dog",
    price: 30.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35011,
    width: 32,
    height: 22,
    length: 26,
    weight: 29,
    type: "wooden",
  },
  {
    id: 12,
    title: "Pluto Yellow Dog",
    price: 28.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35012,
    width: 28,
    height: 41,
    length: 60,
    weight: 44,
    type: "stuffed",
  },
  {
    id: 13,
    title: "Caterpillar",
    price: 18.0,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35012,
    width: 28,
    height: 41,
    length: 60,
    weight: 44,
    type: "wooden",
  },
  {
    id: 14,
    title: "Grey Elephant",
    price: 45.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35009,
    width: 38,
    height: 32,
    length: 24,
    weight: 25,
    type: "stuffed",
  },
  {
    id: 15,
    title: "Wooden Tractor",
    price: 22,
    img: "",
    text: "Our wooden toys are made of 100% natural, sustainable wood—safe, non-toxic, with a gentle touch perfect for little hands. Each piece sparks creativity and hands-on skills, boosting fine motor development and imagination. More durable than plastic alternatives, they blend craftsmanship with educational value, making them a great choice for play and growth.",
    sku: 35010,
    width: 30,
    height: 31,
    length: 20,
    weight: 22,
    type: "wooden",
  },
  {
    id: 16,
    title: "Funny Clown",
    price: 24.0,
    img: "",
    text: "Our stuffed animals feature ultra-soft, non-toxic fabric and fluffy filling—gentle on kids’ skin for cozy cuddles. With vivid, fade-resistant colors, they spark imagination and offer comforting companionship for playtime and bedtime.",
    sku: 35011,
    width: 32,
    height: 22,
    length: 26,
    weight: 29,
    type: "stuffed",
  },
 
];

export default goods;
